sudo: true
language: rust
os:
  - linux
  - osx
rust:
  - nightly
cache: cargo
before_install:
- sudo apt-get upate
- sudo apt-get install make stack
- stack upgrade
script:
- make build && make test
