sudo: true
language: rust
os:
  - linux
  - osx
rust:
  - nightly
cache: cargo
before_install:
- sudo apt-get update
- sudo apt-get install make haskell-stack
- stack upgrade
script:
- make build && make test
