sudo: true
language: rust
os:
  - linux
  - osx
rust:
  - stable
before_install:
- sudo apt-get update
- sudo apt-get install make libgmp-dev
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- stack config set system-ghc --global true
- export PATH=/opt/ghc/8.0.1/bin:$PATH
- stack setup
script:
- make test
