sudo: true
language: rust
os:
  - linux
  - osx
rust:
  - nightly
cache: cargo
before_install:
- sudo apt-get update
- sudo apt-get install make
- curl -sSL https://get.haskellstack.org/ | sh
script:
- make build && make test
